# on:
#   push:
#     branches: 
#       - dev
#       - preprod
      # - prod

on:
  workflow_dispatch:
    inputs:
      environment:
        description:
          choix de de l'environnement
        required: true
        default: 'preprod'
        type: choice
        options:
          - dev
          - preprod
          - prod


jobs:
  choix_env:
    runs-on: ubuntu-latest
    outputs:
      monenv: ${{ steps.verif_env.outputs.monenv }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: verif env
        id: verif_env
        uses: ./.github/actions/environment # chemin d'accès au action.yml

  affichagevarariable:
    needs: choix_env
    runs-on: ubuntu-latest
    environment: ${{ needs.choix_env.outputs.monenv }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: affichage_env
        run: |
          echo ${{ needs.choix_env.outputs.monenv }}
          echo ${{ vars.MAVARIABLE }}

  hello_world_job:
    runs-on: ubuntu-latest
    name: A job to say hellos
    steps:
      - uses: actions/checkout@v4
      - name: searchfilescripthelloworld 
        uses: ./.github/actions/hello_world # chemin d'accès au action.yml
        with:
          monnom: 'Léo'
